// Vercel serverless proxy for the Wake share/OG landing page.
//
// The OG HTML is generated by the Supabase Edge Function `share-itinerary`,
// but Supabase forces `content-type: text/plain` + a sandbox CSP on its default
// *.supabase.co domain (anti-phishing), so social crawlers won't parse the OG
// tags. This proxy fetches that HTML and re-serves it with the correct
// `text/html` content type from the branded waketravel.app domain.

const UPSTREAM = "https://mbuhsdqmobjanyonbtnx.supabase.co/functions/v1/share-itinerary";

module.exports = async (req, res) => {
  const id = (req.query && req.query.id) ? String(req.query.id) : "";
  try {
    const r = await fetch(`${UPSTREAM}?id=${encodeURIComponent(id)}`);
    const html = await r.text();
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res.setHeader("Cache-Control", "public, max-age=300");
    res.status(200).send(html);
  } catch (e) {
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res
      .status(200)
      .send(
        '<!doctype html><html lang="it"><head><meta charset="utf-8"/>' +
          '<title>WAKE — Pianifica e vivi i tuoi viaggi</title>' +
          '<meta property="og:title" content="WAKE — Pianifica e vivi i tuoi viaggi"/>' +
          '<meta property="og:description" content="Pianifica i viaggi, vivili in tempo reale e scopri itinerari dei migliori creator."/>' +
          '</head><body></body></html>'
      );
  }
};
